### ISSUE TITLE
[AN] feat: Firebase Analytics 로그 추가

### ISSUE THREAD

**Issue by krrong** [woowacourse-teams/2023-naaga#114]
## 🔥 구현 기능
Firebase Analytics용 로그를 추가한다.

## 🚧 작업목록
- [ ] Firebase Analytics에 사용할 로그 상수화
- [ ] 버튼 로그 추가

## ⏰ 추정 시간
2h

## 🥸 담당자
크롱

## 👮‍♂️ 리뷰어
빅스, 뽀또

**Comment by briandr97** [comment]
포스트맨으로 작성했습니다.
