### ISSUE TITLE
[BE] 3차 데모데이 구현 사항 기능 정리 및 도메인 설계

### ISSUE THREAD

**Issue by kokodak** [woowacourse-teams/2023-naaga#59]
## 🔥 구현 기능
3차 데모데이 구현 사항 기능 정리 및 도메인 설계

## 🚧 작업목록
- [ ] 구현 기능 정리
- [ ] 도메인 설계

## ⏰ 추정 시간
4시간

## 🥸 담당자
코코닥, 루카, 채채, 이레

**Comment by dooboocookie** [comment]
도메인 설계 마무리되어 클로즈 하겠습니다
